### ISSUE TITLE
XML response comes back as err param

### ISSUE THREAD

**Issue by JarrodMFlesch** [ryanhefner/contentful-sitemap#51]
I am using `sitemap.toXML((xml, err) => { ... }` from the docs, but when I attempt to access `xml` it is undefined, but `err` seems to contain the xml string. Do you know if this is due to an underlying api change from `sitemap`?

I took a look at the code but was not exactly sure how everything was working under the hood to connect with sitemap.

I see you are using `createSitemap` from sitemap - however I could not find the documentation for that function within the sitemap repository. 

If you need more information from me I would be happy to help get to the bottom of this!

**Comment by JarrodMFlesch** [comment]
Ok - I see you are using `sitemap 2.2.0` and that is where the function lives.

**Comment by JarrodMFlesch** [comment]
So I think I can shed some light on this. 

If no function is passed i.e. `const sitemapXML = await sitemap.toXML();` will work because no function is being passed, but if a function is going to be passed down i.e. `sitemap.toXML((xml, err) => { ... }` then the `toXML` will `return callback(null, this.toString());` meaning you would want to access the XML from the second argument coming back from sitemap. Not sure the reasoning behind that sort of API, but it is a pretty old version so that could be half of it.

**Comment by JarrodMFlesch** [comment]
PR open to address this issue #52

**Comment by ryanhefner** [comment]
Fixed/deprecated due to refactoring done for `v1.0.0` release, #58
